apiVersion: v1
kind: Pod
metadata:
  name: manual-deploy-jumphost
spec:
  containers:
  - name: jumphost
    image: debian
    command: ['sleep', 'infinity']
    resources:
      requests:
        memory: "1m"
        cpu: "1m"
