apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"admission.gatekeeper.sh/ignore":"no-self-managing","configmanagement.gke.io/configmanagement":"config-management","control-plane":"controller-manager","gatekeeper.sh/system":"yes","k8s-app":"kubernetes-config-management","policycontroller.configmanagement.gke.io":"true"},"name":"gatekeeper-system","ownerReferences":[{"apiVersion":"configmanagement.gke.io/v1","blockOwnerDeletion":true,"controller":true,"kind":"ConfigManagement","name":"config-management","uid":"78d7f74c-7921-11ea-93de-42010a800178"}]}}
  creationTimestamp: "2020-04-07T23:03:11Z"
  labels:
    admission.gatekeeper.sh/ignore: no-self-managing
    owner: foo
    configmanagement.gke.io/configmanagement: config-management
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
    k8s-app: kubernetes-config-management
    policycontroller.configmanagement.gke.io: "true"
  name: gatekeeper-system
  ownerReferences:
  - apiVersion: configmanagement.gke.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ConfigManagement
    name: config-management
    uid: 78d7f74c-7921-11ea-93de-42010a800178
  resourceVersion: "297496"
  selfLink: /api/v1/namespaces/gatekeeper-system
  uid: f408f437-7923-11ea-93de-42010a800178
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
