apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp
  annotations:
    nomos.dev/cluster-selector: selector-env-dev
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
